import test from 'node:test';
import assert from 'node:assert/strict';
import { JSDOM } from 'jsdom';
import { initThaiDatePickers, enhanceThaiDateInputs, syncThaiDateInputs, todayThai } from '../../src/components/thaiDatePicker.js';
import { modules, groups } from '../../src/data.js';
import { formPage, listPage } from '../../src/views/activities.js';
import { auditPage } from '../../src/views/auditLogs.js';
import { reportBody } from '../../src/reports.js';
import { dashboardContent } from '../../src/dashboard.js';
import { esc, number, thaiDate, moduleHref } from '../../src/utils/format.js';
import { icon } from '../../src/utils/icons.js';

test('Thai calendar integrates with forms, events, dynamic routes, presets and keyboard without a browser', async () => {
  const dom = new JSDOM('<main id="app"><form id="dates" novalidate><label for="start">วันเริ่ม</label><input id="start" class="field" type="date" name="service_date" value="2026-10-09" required data-action="live-filter"><input id="end" class="field" type="date" name="end_date" value="" required><input id="month" type="month" name="month" value="2026-10" disabled></form></main>');
  const { window } = dom;
  globalThis.window = window;
  window.serviceHubUser = { roles: ['super-admin'], permissions: [] };
  window.serviceHubUrls = { apiReportsExport: '/api/reports/export' };
  for (const key of ['document', 'MutationObserver', 'Event', 'FormData']) globalThis[key] = window[key];
  // jsdom has no native dialog implementation. Keyboard/focus handlers still run in the DOM.
  window.HTMLDialogElement.prototype.showModal = function () { this.setAttribute('open', ''); };
  const root = document.getElementById('app');
  const flush = () => new Promise(resolve => setTimeout(resolve, 0));
  const emit = (element, name) => element.dispatchEvent(new window.Event(name, { bubbles: true }));
  const key = (element, name, shiftKey = false) => element.dispatchEvent(new window.KeyboardEvent('keydown', { key: name, shiftKey, bubbles: true, cancelable: true }));
  initThaiDatePickers(root);
  const form = document.getElementById('dates');
  const start = document.getElementById('start');
  const canonical = form.elements.service_date;
  assert.equal(start.type, 'text');
  assert.equal(start.value, '09/10/2569');
  assert.equal(canonical.type, 'hidden');
  assert.equal(new FormData(form).get('service_date'), '2026-10-09');
  assert.equal(new FormData(form).has('month'), false);
  assert.equal(document.getElementById('month-display').disabled, true);
  let changes = 0;
  canonical.addEventListener('change', () => changes++);
  start.value = '10/10/2569'; emit(start, 'input');
  assert.equal(changes, 0);
  emit(start, 'change');
  assert.equal(changes, 1);
  assert.equal(canonical.value, '2026-10-10');
  emit(start, 'change');
  assert.equal(changes, 1);
  start.value = '31/04/2569'; emit(start, 'input'); emit(start, 'change');
  assert.equal(canonical.value, '');
  assert.equal(start.value, '31/04/2569');
  assert.equal(start.checkValidity(), false);
  let submitted = 0;
  form.addEventListener('submit', () => submitted++);
  emit(form, 'submit');
  assert.equal(submitted, 0);
  canonical.value = '2026-10-09'; syncThaiDateInputs(form);
  const open = start.parentElement.querySelector('button');
  open.click();
  let dialog = document.querySelector('dialog');
  assert.match(dialog.textContent, /ตุลาคม พ.ศ. 2569/);
  assert.match(dialog.textContent, /วันนี้/);
  assert.equal(document.activeElement.dataset.value, '2026-10-09');
  key(document.activeElement, 'ArrowRight');
  assert.equal(document.activeElement.dataset.value, '2026-10-10');
  key(dialog, 'Escape');
  assert.equal(document.querySelector('dialog'), null);
  assert.equal(document.activeElement, start);
  open.click(); dialog = document.querySelector('dialog');
  dialog.querySelector('[data-value="2026-10-12"]').click();
  assert.equal(start.value, '12/10/2569');
  assert.equal(canonical.value, '2026-10-12');
  assert.equal(changes, 2);
  open.click(); dialog = document.querySelector('dialog');
  dialog.querySelector('[data-calendar="clear"]').click();
  assert.equal(start.value, '');
  assert.equal(canonical.value, '');
  assert.equal(start.checkValidity(), false);
  open.click(); dialog = document.querySelector('dialog');
  dialog.querySelector('[data-calendar="today"]').click();
  assert.equal(canonical.value, todayThai());
  // Presets and report mode write canonical controls; the display follows explicitly.
  canonical.value = '2026-01-01'; form.elements.end_date.value = '2026-01-31';
  form.elements.month.disabled = false;
  syncThaiDateInputs(form);
  assert.equal(start.value, '01/01/2569');
  assert.equal(document.getElementById('end').value, '31/01/2569');
  assert.equal(document.getElementById('month-display').disabled, false);
  const month = document.getElementById('month-display');
  month.parentElement.querySelector('button').click();
  document.querySelector('dialog [data-value="2026-02"]').click();
  assert.equal(month.value, '02/2569');
  assert.equal(form.elements.month.value, '2026-02');
  month.value = '12/2569'; emit(month, 'input'); emit(month, 'change');
  assert.equal(form.elements.month.value, '2026-12');
  enhanceThaiDateInputs(root); enhanceThaiDateInputs(root);
  assert.equal(root.querySelectorAll('[data-thai-display]').length, 3);
  open.click();
  root.innerHTML = '<form><input id="new-date" type="date" name="from" value="2024-02-29"></form>';
  await flush();
  assert.equal(document.querySelector('dialog'), null);
  assert.equal(document.getElementById('new-date').value, '29/02/2567');
  assert.equal(root.querySelectorAll('input[type="date"],input[type="month"]').length, 0);
  document.getElementById('new-date').parentElement.querySelector('button').click();
  const finalDialog = document.querySelector('dialog');
  const first = finalDialog.querySelector('[data-calendar="close"]');
  const last = finalDialog.querySelector('[data-calendar="today"]');
  last.focus(); key(last, 'Tab'); assert.equal(document.activeElement, first);
  key(first, 'Tab', true); assert.equal(document.activeElement, last);
  key(finalDialog, 'Escape');
  // Every date-bearing page uses the same enhancement, including error rerenders.
  const checkPage = async (html, count) => {
    root.innerHTML = html;
    await flush();
    assert.equal(root.querySelectorAll('[data-thai-display]').length, count);
    assert.equal(root.querySelectorAll('input[type="date"],input[type="month"]').length, 0);
  };
  for (const module of modules) {
    await checkPage(formPage({ module, record: { id: 1, service_date: '2026-10-09', end_date: '2026-10-10' } }), module.id === 'waste-collections' ? 2 : 1);
    assert.equal(new FormData(root.querySelector('form')).get('service_date'), '2026-10-09');
    await checkPage(listPage({ module, params: new URLSearchParams() }), 2);
  }
  await checkPage(auditPage({ params: new URLSearchParams(), auditRows: [] }), 2);
  await checkPage(dashboardContent({ loading: true, error: '', params: new URLSearchParams(), modules, groups, icon, esc, number, moduleHref }), 2);
  await checkPage(reportBody({ module: null, params: new URLSearchParams(), loading: true, error: '', modules, groups, can: () => true, esc, number, thaiDate, moduleHref }), 3);
  await checkPage(formPage({ module: modules[0], errors: { service_date: 'วันที่ไม่ถูกต้อง' }, values: { service_date: '2026-10-09' } }), 1);
  assert.equal(document.getElementById('field-service_date').value, '09/10/2569');
  assert.equal(document.getElementById('field-service_date').getAttribute('aria-invalid'), 'true');
  dom.window.close();
});
