export const groups = [
  { id: 'cleaning', label: 'งานบริการรักษาความสะอาด', short: 'รักษาความสะอาด', icon: 'sparkles', tone: 'mint' },
  { id: 'waste', label: 'งานบริการมูลฝอย', short: 'บริการมูลฝอย', icon: 'recycle', tone: 'sky' },
  { id: 'sanitation', label: 'งานบริหารจัดการสิ่งปฏิกูล', short: 'จัดการสิ่งปฏิกูล', icon: 'droplet', tone: 'amber' },
  { id: 'projects', label: 'งานพัฒนาระบบจัดการมูลฝอย', short: 'พัฒนาระบบ', icon: 'chart', tone: 'violet' },
];

const date = { name: 'service_date', label: 'วันที่ดำเนินงาน', type: 'date', required: true };


export const modules = [
  { id: 'road-washings', group: 'cleaning', label: 'การล้างทำความสะอาดถนน ลดฝุ่น และพัฒนาเขตรักษาความสะอาด', short: 'การล้างทำความสะอาดถนน ลดฝุ่น และพัฒนาเขตรักษาความสะอาด', icon: 'road', titleField: 'location', fields: [date, { name: 'cleaning_zone_id', label: 'เขตรักษาความสะอาด', type: 'reference', reference: 'cleaning-zones', required: true }, { name: 'location', label: 'สถานที่', type: 'text', required: true }, { name: 'distance_km', label: 'ระยะทาง', type: 'number', unit: 'กม.', required: true }] },
  { id: 'waterway-cleanings', group: 'cleaning', label: 'การกำจัดผักตบชวาและมูลฝอยในคลองสาธารณะ', short: 'การกำจัดผักตบชวาและมูลฝอยในคลองสาธารณะ', icon: 'waves', titleField: 'waterway_name', fields: [date, { name: 'waterway_name', label: 'ชื่อแหล่งน้ำ', type: 'text', required: true }, { name: 'distance_km', label: 'ระยะทางปฏิบัติงาน', type: 'number', unit: 'กม.', required: true }, { name: 'quantity', label: 'ปริมาณที่กำจัดได้', type: 'number', unit: 'ตัน', required: true }] },
  { id: 'road-sweepings', group: 'cleaning', label: 'การกวาดทำความสะอาดฝุ่นถนนสาธารณะ', short: 'การกวาดทำความสะอาดฝุ่นถนนสาธารณะ', icon: 'sparkles', titleField: 'road', fields: [date, { name: 'road', label: 'ถนน', type: 'text', required: true }, { name: 'storage_location', label: 'สถานที่จัดเก็บ', type: 'text', required: true }, { name: 'distance_km', label: 'ระยะทาง', type: 'number', unit: 'กม.', required: true }] },
  { id: 'outsourced-cleanings', group: 'cleaning', label: 'กิจกรรมจ้างเหมาบุคคลภายนอกรักษาความสะอาดและพัฒนาสิ่งแวดล้อม', short: 'กิจกรรมจ้างเหมาบุคคลภายนอกรักษาความสะอาดและพัฒนาสิ่งแวดล้อม', icon: 'users', titleField: 'location', fields: [date, { name: 'location', label: 'สถานที่', type: 'text', required: true }, { name: 'distance_km', label: 'ระยะทาง', type: 'number', unit: 'กม.', required: true }, { name: 'community', label: 'ชุมชน', type: 'text', required: true }] },
  { id: 'waste-collections', group: 'waste', label: 'งานบริหารจัดการมูลฝอย', short: 'งานบริหารจัดการมูลฝอย', icon: 'recycle', titleField: 'waste_name', fields: [date, { name: 'source', label: 'แหล่งที่เก็บ', type: 'text', required: true }, { name: 'waste_type_id', label: 'ประเภทขยะมูลฝอย', type: 'reference', reference: 'waste-types', required: true }, { name: 'waste_name', label: 'ชื่อขยะมูลฝอย', type: 'text', required: true }, { name: 'weight', label: 'น้ำหนัก', type: 'number', unit: 'ตัน', required: true }] },
  { id: 'drain-cleanings', group: 'sanitation', label: 'งานลอกท่อระบายน้ำ', short: 'ลอกท่อระบายน้ำ', icon: 'droplet', titleField: 'location', fields: [date, { name: 'location', label: 'สถานที่', type: 'text', required: true }, { name: 'distance_km', label: 'ระยะทาง', type: 'number', unit: 'กม.', required: true }, { name: 'sediment_quantity', label: 'ปริมาณตะกอน', type: 'number', unit: 'ลบ.ม.', required: true }] },
  { id: 'septic-pumpings', group: 'sanitation', label: 'งานสูบสิ่งปฏิกูล', short: 'สูบสิ่งปฏิกูล', icon: 'truck', titleField: 'location', fields: [date, { name: 'location', label: 'สถานที่', type: 'text', required: true }, { name: 'volume', label: 'ปริมาตรสิ่งปฏิกูล', type: 'number', unit: 'ลบ.ม.', required: true }, { name: 'fee_amount', label: 'ค่าธรรมเนียม', type: 'number', unit: 'บาท', required: true }] },
  { id: 'septic-treatments', group: 'sanitation', label: 'การบำบัดสิ่งปฏิกูล', short: 'บำบัดสิ่งปฏิกูล', icon: 'flask', titleField: 'service_date', fields: [date, { name: 'sludge_quantity', label: 'ปริมาณตะกอนสำหรับทำปุ๋ย', type: 'number', unit: 'กก.', required: true }, { name: 'fertilizer_remaining', label: 'ปุ๋ยอินทรีย์สูตร 2 คงเหลือ', type: 'number', unit: 'กก.', required: true }, { name: 'microbial_note', label: 'ข้อมูลการใส่น้ำจุลินทรีย์ชีวภาพ', type: 'textarea', required: true }] },
  { id: 'waste-management-projects', group: 'projects', label: 'โครงการพัฒนาระบบจัดการมูลฝอย', short: 'โครงการพัฒนา', icon: 'chart', titleField: 'project_name', fields: [date, { name: 'project_name', label: 'ชื่อโครงการ', type: 'text', required: true }, { name: 'communities_count', label: 'จำนวนชุมชนที่เข้าร่วม', type: 'integer', unit: 'ชุมชน', required: true }, { name: 'participants_count', label: 'ผู้เข้าร่วมโครงการ', type: 'integer', unit: 'คน', required: true }] },
];

